### ISSUE TITLE
Users on Python 3.7 only find unusable `dev1` version and can't update

### ISSUE THREAD

**Issue by torsava** [fedora-python/ferrypick#3]
Hi,
ferrypick installed (--user) from PyPI doesn't work. It fails with:

    $ ferrypick --help
    Traceback (most recent call last):
      File "/home/torsava/.local/bin/ferrypick", line 5, in <module>
        from ferrypick import main
    ModuleNotFoundError: No module named 'ferrypick'

Steps to reproduce:

    $ pip install --user ferrypick
    $ ferrypick --help

It seems the module actually isn't there. When uninstalling ferrypick, only the binary and dist-info are listed:

    $ pip uninstall ferrypick
    Found existing installation: ferrypick 0.1.dev1
    Uninstalling ferrypick-0.1.dev1:
      Would remove:
        /home/torsava/.local/bin/ferrypick
        /home/torsava/.local/lib/python3.7/site-packages/ferrypick-0.1.dev1.dist-info/*
    Proceed (y/n)?

**Comment by hroncok** [comment]
This was supposed to be fixed in dev2. You have dev1 installed. Can you reproduce if you upgrade the package?

**Comment by hroncok** [comment]
The fixer was 1eb8b6476ad0983ad295a31427c74c9bf858548c

**Comment by torsava** [comment]
For some reason I am not able to install that version:

    $ pip install --user ferrypick==0.1.dev2
    ERROR: Could not find a version that satisfies the requirement ferrypick==0.1.dev2 (from versions: 0.1.dev1)
    ERROR: No matching distribution found for ferrypick==0.1.dev2

I tripple checked the version, being a dyslexic, but can't find any issue.

**Comment by torsava** [comment]
It is available on PyPI website, so I'm stumped: https://pypi.org/project/ferrypick/0.1.dev2/#history

**Comment by torsava** [comment]
Oooh, got it. I'm using Python 3.7 and the `dev2` version is labeled as Python 3.8 or higher.

**Comment by torsava** [comment]
The first one isn't though, so it installed and refused to update.

**Comment by torsava** [comment]
`dev2` version works. I'm renaming the issue to address the left over unusable `dev1` version.

**Comment by hroncok** [comment]
The code is 3.7 incompatible. The packaging issues made it possible to install dev1 on 3.7, but without the actual code. The only way I can think of to fix this is to remove dev1 from PyPI.

**Comment by torsava** [comment]
> The code is 3.7 incompatible. The packaging issues made it possible to install dev1 on 3.7, but without the actual code. The only way I can think of to fix this is to remove dev1 from PyPI.

I would say that's a good idea.

**Comment by hroncok** [comment]
We can either yank or delete it, I'll figure out what is more appropriate https://twitter.com/di_codes/status/1253166894158417926

**Comment by hroncok** [comment]
I figure we should yank it. Yank is reversible, so I've done it now.

**Comment by hroncok** [comment]
```
[tmp]$ python3.8 -m venv __venv38__
[tmp]$ . __venv38__/bin/activate
(__venv38__) [tmp]$ pip install ferrypick==0.1.dev1
WARNING: The candidate selected for download or install is a yanked version: 'ferrypick' candidate (version 0.1.dev1 at https://files.pythonhosted.org/packages/b5/0e/04a44db1f3ce963f489f8582b92471ff60ef3c14bd90b4a5913e8e80aab1/ferrypick-0.1.dev1-py3-none-any.whl#sha256=110adcd8cf71f35c9926388e7b380103e1f22c2ebcdc8bd9acca16e405193782 (from https://pypi.org/simple/ferrypick/))
Reason for being yanked: This release is entirely broken, and it also doesn't block installation from Python version not supported by the later versions. Hence users of e.g. Python 3.7 would always get this broken version without a reasonable information about ferrypick requiring Python 3.8+.
Collecting ferrypick==0.1.dev1
  Using cached https://files.pythonhosted.org/packages/b5/0e/04a44db1f3ce963f489f8582b92471ff60ef3c14bd90b4a5913e8e80aab1/ferrypick-0.1.dev1-py3-none-any.whl
Installing collected packages: ferrypick
Successfully installed ferrypick-0.1.dev1
WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

The above is not perfect, but only affects users who pin.


```
[tmp]$ python3.7 -m venv __venv37__
[tmp]$ . __venv37__/bin/activate
(__venv37__) [tmp]$ pip install ferrypick
WARNING: The candidate selected for download or install is a yanked version: 'ferrypick' candidate (version 0.1.dev1 at https://files.pythonhosted.org/packages/b5/0e/04a44db1f3ce963f489f8582b92471ff60ef3c14bd90b4a5913e8e80aab1/ferrypick-0.1.dev1-py3-none-any.whl#sha256=110adcd8cf71f35c9926388e7b380103e1f22c2ebcdc8bd9acca16e405193782 (from https://pypi.org/simple/ferrypick/))
Reason for being yanked: This release is entirely broken, and it also doesn't block installation from Python version not supported by the later versions. Hence users of e.g. Python 3.7 would always get this broken version without a reasonable information about ferrypick requiring Python 3.8+.
Collecting ferrypick
  Using cached https://files.pythonhosted.org/packages/b5/0e/04a44db1f3ce963f489f8582b92471ff60ef3c14bd90b4a5913e8e80aab1/ferrypick-0.1.dev1-py3-none-any.whl
Installing collected packages: ferrypick
Successfully installed ferrypick-0.1.dev1
WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

That is bad either way :/

**Comment by hroncok** [comment]
I wonder if this is expected behavior of pip. https://github.com/pypa/pip/issues/8262

**Comment by torsava** [comment]
Yeah, not perfect. I would consider deleting it outright, but either way is reasonable enough.

**Comment by torsava** [comment]
Thanks!

**Comment by hroncok** [comment]
> I would consider deleting it outright, but either way is reasonable enough.

I am not deleting it now, because I want to use it as a reproducer for the pip issue. If they deem the behavior appropriate, I'll delete it.
